/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Sebastian Burgos
 */
public class Acueducto extends javax.swing.JFrame {

    /**
     * Creates new form Acueducto
     */
    public Acueducto() {
        setResizable(false);
        setSize(953, 620);
        this.setLocationRelativeTo(null);

        initComponents();

        this.pnlHome.setVisible(true);
        this.pnlAdd.setVisible(false);
        this.pnlEdit.setVisible(false);
        this.pnlSearch.setVisible(false);
        this.pnlList.setVisible(false);
        this.pnlPay.setVisible(false);
        this.pnlPdf.setVisible(false);
        this.pnlDelete.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRoot = new javax.swing.JPanel();
        pnlSide = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnList = new javax.swing.JButton();
        btnPay = new javax.swing.JButton();
        btnPdf = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        pnlCentral = new javax.swing.JPanel();
        pnlHome = new FondoPaneles();
        jLabel8 = new javax.swing.JLabel();
        pnlAdd = new FondoPaneles();
        btnAddSuscriptor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pnlEdit = new FondoPaneles();
        jLabel2 = new javax.swing.JLabel();
        btnEditFecha = new javax.swing.JButton();
        btnEditSuscriptor = new javax.swing.JButton();
        pnlSearch = new FondoPaneles();
        jLabel3 = new javax.swing.JLabel();
        btnSearchSuscriptor = new javax.swing.JButton();
        pnlList = new FondoPaneles();
        jLabel4 = new javax.swing.JLabel();
        btnListSuscriptor = new javax.swing.JButton();
        pnlPay = new FondoPaneles();
        jLabel5 = new javax.swing.JLabel();
        btnPaySuscriptor = new javax.swing.JButton();
        pnlPdf = new FondoPaneles();
        btnPdfGenerar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        pnlDelete = new FondoPaneles();
        jLabel7 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlRoot.setMaximumSize(new java.awt.Dimension(1000, 600));
        pnlRoot.setPreferredSize(new java.awt.Dimension(1000, 600));
        pnlRoot.setLayout(new java.awt.BorderLayout());

        pnlSide.setMaximumSize(null);
        pnlSide.setPreferredSize(new java.awt.Dimension(100, 33));

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-home-32.png"))); // NOI18N
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        pnlSide.add(btnHome);

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-add-new-32.png"))); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        pnlSide.add(btnAdd);

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-edit-32.png"))); // NOI18N
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        pnlSide.add(btnEdit);

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-search-32.png"))); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        pnlSide.add(btnSearch);

        btnList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-list-32.png"))); // NOI18N
        btnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListActionPerformed(evt);
            }
        });
        pnlSide.add(btnList);

        btnPay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-money-bag-32.png"))); // NOI18N
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });
        pnlSide.add(btnPay);

        btnPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-pdf-32.png"))); // NOI18N
        btnPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPdfActionPerformed(evt);
            }
        });
        pnlSide.add(btnPdf);

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-delete-32.png"))); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        pnlSide.add(btnDelete);

        pnlRoot.add(pnlSide, java.awt.BorderLayout.WEST);
        pnlSide.getAccessibleContext().setAccessibleParent(pnlSide);

        pnlCentral.setLayout(new javax.swing.OverlayLayout(pnlCentral));

        //pnlInicio.setBackground(new java.awt.Color(41, 41, 41));
        //pnlInicio.setPreferredSize(new java.awt.Dimension(853, 538));

        jLabel8.setFont(new java.awt.Font("Lucida Calligraphy", 3, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("\"La bebida más peligrosa es el agua, te mata si no la bebes\"");

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel8)
                .addContainerGap(485, Short.MAX_VALUE))
        );

        pnlCentral.add(pnlHome);

        btnAddSuscriptor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-add-user-male-50.png"))); // NOI18N
        btnAddSuscriptor.setText("Suscriptor");
        btnAddSuscriptor.setAlignmentX(0.5F);
        btnAddSuscriptor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddSuscriptor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddSuscriptor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSuscriptorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu Agregar");

        javax.swing.GroupLayout pnlAddLayout = new javax.swing.GroupLayout(pnlAdd);
        pnlAdd.setLayout(pnlAddLayout);
        pnlAddLayout.setHorizontalGroup(
            pnlAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddLayout.createSequentialGroup()
                .addGroup(pnlAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddLayout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlAddLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btnAddSuscriptor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 368, Short.MAX_VALUE)))
                .addGap(342, 342, 342))
        );
        pnlAddLayout.setVerticalGroup(
            pnlAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnAddSuscriptor)
                .addContainerGap(469, Short.MAX_VALUE))
        );

        pnlCentral.add(pnlAdd);

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Menu Editar");

        btnEditFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-edit-calendar-50.png"))); // NOI18N
        btnEditFecha.setText("Fecha");
        btnEditFecha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditFecha.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditFechaActionPerformed(evt);
            }
        });

        btnEditSuscriptor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-registration-50.png"))); // NOI18N
        btnEditSuscriptor.setText("Suscriptor");
        btnEditSuscriptor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditSuscriptor.setVerifyInputWhenFocusTarget(false);
        btnEditSuscriptor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditSuscriptor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditSuscriptorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEditLayout = new javax.swing.GroupLayout(pnlEdit);
        pnlEdit.setLayout(pnlEditLayout);
        pnlEditLayout.setHorizontalGroup(
            pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditLayout.createSequentialGroup()
                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEditLayout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                    .addGroup(pnlEditLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btnEditSuscriptor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(btnEditFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(354, 354, 354))
        );
        pnlEditLayout.setVerticalGroup(
            pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditSuscriptor)
                    .addComponent(btnEditFecha))
                .addContainerGap(469, Short.MAX_VALUE))
        );

        pnlCentral.add(pnlEdit);

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Menu Buscar");

        btnSearchSuscriptor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-find-user-male-50.png"))); // NOI18N
        btnSearchSuscriptor.setText("Buscar");
        btnSearchSuscriptor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSearchSuscriptor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSearchSuscriptor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchSuscriptorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSearchLayout = new javax.swing.GroupLayout(pnlSearch);
        pnlSearch.setLayout(pnlSearchLayout);
        pnlSearchLayout.setHorizontalGroup(
            pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchLayout.createSequentialGroup()
                .addGroup(pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSearchLayout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                    .addGroup(pnlSearchLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btnSearchSuscriptor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(367, 367, 367))
        );
        pnlSearchLayout.setVerticalGroup(
            pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(btnSearchSuscriptor)
                .addContainerGap(469, Short.MAX_VALUE))
        );

        pnlCentral.add(pnlSearch);

        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Menu Listar");

        btnListSuscriptor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-list-view-50.png"))); // NOI18N
        btnListSuscriptor.setText("Listar");
        btnListSuscriptor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnListSuscriptor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnListSuscriptor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListSuscriptorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlListLayout = new javax.swing.GroupLayout(pnlList);
        pnlList.setLayout(pnlListLayout);
        pnlListLayout.setHorizontalGroup(
            pnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListLayout.createSequentialGroup()
                .addGroup(pnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlListLayout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                    .addGroup(pnlListLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btnListSuscriptor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(369, 369, 369))
        );
        pnlListLayout.setVerticalGroup(
            pnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(btnListSuscriptor)
                .addContainerGap(469, Short.MAX_VALUE))
        );

        pnlCentral.add(pnlList);

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Menu Pagar");

        btnPaySuscriptor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-salary-male-50.png"))); // NOI18N
        btnPaySuscriptor.setText("Pagar");
        btnPaySuscriptor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPaySuscriptor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPaySuscriptor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaySuscriptorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPayLayout = new javax.swing.GroupLayout(pnlPay);
        pnlPay.setLayout(pnlPayLayout);
        pnlPayLayout.setHorizontalGroup(
            pnlPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPayLayout.createSequentialGroup()
                .addGap(343, 343, 343)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addGap(369, 369, 369))
            .addGroup(pnlPayLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(btnPaySuscriptor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPayLayout.setVerticalGroup(
            pnlPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(btnPaySuscriptor)
                .addContainerGap(469, Short.MAX_VALUE))
        );

        pnlCentral.add(pnlPay);

        btnPdfGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-export-pdf-50.png"))); // NOI18N
        btnPdfGenerar.setText("PDFs");
        btnPdfGenerar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPdfGenerar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPdfGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPdfGenerarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Menu Generar PDF");

        javax.swing.GroupLayout pnlPdfLayout = new javax.swing.GroupLayout(pnlPdf);
        pnlPdf.setLayout(pnlPdfLayout);
        pnlPdfLayout.setHorizontalGroup(
            pnlPdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPdfLayout.createSequentialGroup()
                .addGroup(pnlPdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPdfLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btnPdfGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPdfLayout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)))
                .addGap(319, 319, 319))
        );
        pnlPdfLayout.setVerticalGroup(
            pnlPdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPdfLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(btnPdfGenerar)
                .addContainerGap(469, Short.MAX_VALUE))
        );

        pnlCentral.add(pnlPdf);

        jLabel7.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Menu Eliminar");

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-delete-user-male-50.png"))); // NOI18N
        btnEliminar.setText("ELiminar");
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDeleteLayout = new javax.swing.GroupLayout(pnlDelete);
        pnlDelete.setLayout(pnlDeleteLayout);
        pnlDeleteLayout.setHorizontalGroup(
            pnlDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeleteLayout.createSequentialGroup()
                .addGroup(pnlDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDeleteLayout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                    .addGroup(pnlDeleteLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(332, 332, 332))
        );
        pnlDeleteLayout.setVerticalGroup(
            pnlDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeleteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addContainerGap(469, Short.MAX_VALUE))
        );

        pnlCentral.add(pnlDelete);

        pnlRoot.add(pnlCentral, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlRoot, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if (pnlAdd.isVisible()) {
            pnlHome.setVisible(false);
            pnlEdit.setVisible(false);
            pnlSearch.setVisible(false);
            pnlList.setVisible(false);
            pnlPay.setVisible(false);
            pnlPdf.setVisible(false);
            pnlDelete.setVisible(false);
        } else {
            pnlHome.setVisible(false);
            pnlAdd.setVisible(true);
            pnlEdit.setVisible(false);
            pnlSearch.setVisible(false);
            pnlList.setVisible(false);
            pnlPay.setVisible(false);
            pnlPdf.setVisible(false);
            pnlDelete.setVisible(false);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        pnlHome.setVisible(true);
        pnlAdd.setVisible(false);
        pnlEdit.setVisible(false);
        pnlSearch.setVisible(false);
        pnlList.setVisible(false);
        pnlPay.setVisible(false);
        pnlPdf.setVisible(false);
        pnlDelete.setVisible(false);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if (pnlEdit.isVisible()) {
            pnlHome.setVisible(false);
            pnlAdd.setVisible(false);
            pnlSearch.setVisible(false);
            pnlList.setVisible(false);
            pnlPay.setVisible(false);
            pnlPdf.setVisible(false);
            pnlDelete.setVisible(false);
        } else {
            pnlHome.setVisible(false);
            pnlAdd.setVisible(false);
            pnlEdit.setVisible(true);
            pnlSearch.setVisible(false);
            pnlList.setVisible(false);
            pnlPay.setVisible(false);
            pnlPdf.setVisible(false);
            pnlDelete.setVisible(false);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnAddSuscriptorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSuscriptorActionPerformed
        // TODO add your handling code here:
        RegistrarSuscriptor registro = new RegistrarSuscriptor();
        registro.setVisible(true);
        registro.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.dispose();
        registro.addWindowListener(reAbrir());
    }//GEN-LAST:event_btnAddSuscriptorActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        if (pnlSearch.isVisible()) {
            pnlHome.setVisible(false);
            pnlAdd.setVisible(false);
            pnlEdit.setVisible(false);
            pnlList.setVisible(false);
            pnlPay.setVisible(false);
            pnlPdf.setVisible(false);
            pnlDelete.setVisible(false);
        } else {
            pnlHome.setVisible(false);
            pnlAdd.setVisible(false);
            pnlEdit.setVisible(false);
            pnlSearch.setVisible(true);
            pnlList.setVisible(false);
            pnlPay.setVisible(false);
            pnlPdf.setVisible(false);
            pnlDelete.setVisible(false);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
        // TODO add your handling code here:
        if (pnlList.isVisible()) {
            pnlHome.setVisible(false);
            pnlAdd.setVisible(false);
            pnlEdit.setVisible(false);
            pnlSearch.setVisible(false);
            pnlPay.setVisible(false);
            pnlPdf.setVisible(false);
            pnlDelete.setVisible(false);
        } else {
            pnlHome.setVisible(false);
            pnlAdd.setVisible(false);
            pnlEdit.setVisible(false);
            pnlSearch.setVisible(false);
            pnlList.setVisible(true);
            pnlPay.setVisible(false);
            pnlPdf.setVisible(false);
            pnlDelete.setVisible(false);
        }
    }//GEN-LAST:event_btnListActionPerformed

    private void btnPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPdfActionPerformed
        // TODO add your handling code here:
        if (pnlPdf.isVisible()) {
            pnlHome.setVisible(false);
            pnlAdd.setVisible(false);
            pnlEdit.setVisible(false);
            pnlSearch.setVisible(false);
            pnlList.setVisible(false);
            pnlPay.setVisible(false);
            pnlDelete.setVisible(false);
        } else {
            pnlHome.setVisible(false);
            pnlAdd.setVisible(false);
            pnlEdit.setVisible(false);
            pnlSearch.setVisible(false);
            pnlList.setVisible(false);
            pnlPay.setVisible(false);
            pnlPdf.setVisible(true);
            pnlDelete.setVisible(false);
        }
    }//GEN-LAST:event_btnPdfActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        // TODO add your handling code here:
        if (pnlPay.isVisible()) {
            pnlHome.setVisible(false);
            pnlAdd.setVisible(false);
            pnlEdit.setVisible(false);
            pnlSearch.setVisible(false);
            pnlList.setVisible(false);
            pnlPdf.setVisible(false);
            pnlDelete.setVisible(false);
        } else {
            pnlHome.setVisible(false);
            pnlAdd.setVisible(false);
            pnlEdit.setVisible(false);
            pnlSearch.setVisible(false);
            pnlList.setVisible(false);
            pnlPay.setVisible(true);
            pnlPdf.setVisible(false);
            pnlDelete.setVisible(false);
        }
    }//GEN-LAST:event_btnPayActionPerformed

    private void btnPaySuscriptorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaySuscriptorActionPerformed
        // TODO add your handling code here:
        PagarSuscriptor pagar = new PagarSuscriptor();
        pagar.setVisible(true);
        pagar.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.dispose();
        pagar.addWindowListener(reAbrir());
    }//GEN-LAST:event_btnPaySuscriptorActionPerformed

    private void btnPdfGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPdfGenerarActionPerformed
        // TODO add your handling code here:
        GenerarFactura f = new GenerarFactura();
        f.setVisible(true);
        f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.dispose();
        f.addWindowListener(reAbrir());
    }//GEN-LAST:event_btnPdfGenerarActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (pnlDelete.isVisible()) {
            pnlHome.setVisible(false);
            pnlAdd.setVisible(false);
            pnlEdit.setVisible(false);
            pnlSearch.setVisible(false);
            pnlList.setVisible(false);
            pnlPay.setVisible(false);
            pnlPdf.setVisible(false);
        } else {
            pnlHome.setVisible(false);
            pnlAdd.setVisible(false);
            pnlEdit.setVisible(false);
            pnlSearch.setVisible(false);
            pnlList.setVisible(false);
            pnlPay.setVisible(false);
            pnlPdf.setVisible(false);
            pnlDelete.setVisible(true);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditSuscriptorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditSuscriptorActionPerformed
        // TODO add your handling code here:
        EditarSuscriptor registro = new EditarSuscriptor();
        registro.setVisible(true);
        registro.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.dispose();
        registro.addWindowListener(reAbrir());
    }//GEN-LAST:event_btnEditSuscriptorActionPerformed

    private void btnEditFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditFechaActionPerformed
        // TODO add your handling code here:
        ActualizarFechas actualizarFechas = new ActualizarFechas();
        actualizarFechas.setVisible(true);
        actualizarFechas.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.dispose();
        actualizarFechas.addWindowListener(reAbrir());
    }//GEN-LAST:event_btnEditFechaActionPerformed

    private void btnSearchSuscriptorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchSuscriptorActionPerformed
        // TODO add your handling code here:
        BuscarSuscriptor buscar = new BuscarSuscriptor();
        buscar.setVisible(true);
        buscar.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.dispose();
        buscar.addWindowListener(reAbrir());
    }//GEN-LAST:event_btnSearchSuscriptorActionPerformed

    private void btnListSuscriptorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListSuscriptorActionPerformed
        // TODO add your handling code here:
        ListarSuscriptor listarSuscriptor = new ListarSuscriptor();
        listarSuscriptor.setVisible(true);
        listarSuscriptor.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.dispose();
        listarSuscriptor.addWindowListener(reAbrir());
    }//GEN-LAST:event_btnListSuscriptorActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        EliminarSuscriptor delete = new EliminarSuscriptor();
        delete.setVisible(true);
        delete.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.dispose();
        delete.addWindowListener(reAbrir());
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acueducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddSuscriptor;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEditFecha;
    private javax.swing.JButton btnEditSuscriptor;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnList;
    private javax.swing.JButton btnListSuscriptor;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnPaySuscriptor;
    private javax.swing.JButton btnPdf;
    private javax.swing.JButton btnPdfGenerar;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearchSuscriptor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel pnlAdd;
    private javax.swing.JPanel pnlCentral;
    private javax.swing.JPanel pnlDelete;
    private javax.swing.JPanel pnlEdit;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlList;
    private javax.swing.JPanel pnlPay;
    private javax.swing.JPanel pnlPdf;
    private javax.swing.JPanel pnlRoot;
    private javax.swing.JPanel pnlSearch;
    private javax.swing.JPanel pnlSide;
    // End of variables declaration//GEN-END:variables

    public class FondoPaneles extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/images/agua.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

    private WindowListener reAbrir() {
        WindowAdapter adapter = new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent we) {
                Acueducto nuevo = new Acueducto();
                nuevo.setVisible(true);
            }
        };
        return adapter;
    }
}
