/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controller;
import java.awt.Graphics;
import java.awt.PrintJob;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Sebastian Burgos
 */
public class GenerarFactura extends javax.swing.JFrame {

    /**
     * Creates new form GenerarFactura
     */
    public GenerarFactura() {
        setResizable(false);
        setSize(1050, 710);
        this.setLocationRelativeTo(null);
        initComponents();
    }

    Controller controller = new Controller();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlFactura = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFechaDeEmision = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPagoOportuno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFechaSuspension = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMesFacturado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMesesVencidos = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAlcantarillado = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtAseo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtSubsidio = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTarifa = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtFechaUltimoPago = new javax.swing.JTextField();
        txtValorUltimoPago = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtConsumo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtTotalPresente = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtMesesDeuda = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtReconexion = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtTotalOtrosSaldos = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtTotalPagar = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtFacturaNumero = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtNombreSuscriptor = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        txtCodigoSuscriptor = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        txtMesFacturadoSuscriptor = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        txtFEmisionSuscriptor = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        txtPOportunoSuscriptor = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        txtFSuspensionSuscriptor = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txtConsumoSuscriptor = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        txtTPresenteSuscriptor = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtMDeudaSuscriptor = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        txtOSaldosSuscriptor = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        txtReconexionSuscriptor = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        txtMatriculaSuscriptor = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        txtTotalAcueducto = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFactura.setBackground(new java.awt.Color(255, 255, 255));
        pnlFactura.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Emaus.png"))); // NOI18N
        pnlFactura.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, 86));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setLabelFor(txtFechaDeEmision);
        jLabel7.setText("<html>Fecha de <center> Emision<html>");
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        pnlFactura.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 70, 60));

        txtFechaDeEmision.setEditable(false);
        txtFechaDeEmision.setBackground(new java.awt.Color(255, 255, 255));
        txtFechaDeEmision.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        txtFechaDeEmision.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFechaDeEmision.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        txtFechaDeEmision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaDeEmisionActionPerformed(evt);
            }
        });
        pnlFactura.add(txtFechaDeEmision, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 70, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setLabelFor(txtPagoOportuno);
        jLabel8.setText("<html><center>Pago<center>Oportuno<center>Hasta<html>");
        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        pnlFactura.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 70, 60));

        txtPagoOportuno.setEditable(false);
        txtPagoOportuno.setBackground(new java.awt.Color(255, 255, 255));
        txtPagoOportuno.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        txtPagoOportuno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPagoOportuno.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        txtPagoOportuno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPagoOportunoActionPerformed(evt);
            }
        });
        pnlFactura.add(txtPagoOportuno, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 70, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setLabelFor(txtFechaSuspension);
        jLabel6.setText("<html><center>Fecha<center>Suspensión<html>");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        pnlFactura.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 70, 60));

        txtFechaSuspension.setEditable(false);
        txtFechaSuspension.setBackground(new java.awt.Color(255, 255, 255));
        txtFechaSuspension.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        txtFechaSuspension.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFechaSuspension.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        txtFechaSuspension.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaSuspensionActionPerformed(evt);
            }
        });
        pnlFactura.add(txtFechaSuspension, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 70, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ACUEDUCTO");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        pnlFactura.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 160, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setLabelFor(txtNombre);
        jLabel10.setText("NOMBRE DEL SUSCRIPTOR");
        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        pnlFactura.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 190, 20));

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        txtNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        pnlFactura.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 190, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setLabelFor(txtDireccion);
        jLabel9.setText("DIRECCION DEL SUSCRIPTOR");
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        pnlFactura.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 170, 20));

        txtDireccion.setEditable(false);
        txtDireccion.setBackground(new java.awt.Color(255, 255, 255));
        txtDireccion.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        txtDireccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDireccion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        pnlFactura.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 170, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setLabelFor(txtMesFacturado);
        jLabel3.setText("MES FACTURADO");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        pnlFactura.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 110, 20));

        txtMesFacturado.setEditable(false);
        txtMesFacturado.setBackground(new java.awt.Color(255, 255, 255));
        txtMesFacturado.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        txtMesFacturado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMesFacturado.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        txtMesFacturado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMesFacturadoActionPerformed(evt);
            }
        });
        pnlFactura.add(txtMesFacturado, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 110, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setLabelFor(txtMesesVencidos);
        jLabel2.setText("MESES VENCIDOS");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        pnlFactura.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 100, 20));

        txtMesesVencidos.setEditable(false);
        txtMesesVencidos.setBackground(new java.awt.Color(255, 255, 255));
        txtMesesVencidos.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        txtMesesVencidos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMesesVencidos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        txtMesesVencidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMesesVencidosActionPerformed(evt);
            }
        });
        pnlFactura.add(txtMesesVencidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 100, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setLabelFor(txtCodigo);
        jLabel11.setText("CODIGO");
        jLabel11.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        pnlFactura.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 80, 20));

        txtCodigo.setEditable(false);
        txtCodigo.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigo.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        txtCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        pnlFactura.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 80, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setLabelFor(txtAlcantarillado);
        jLabel5.setText("ALCANTARILLADO");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        pnlFactura.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 110, 20));

        txtAlcantarillado.setEditable(false);
        txtAlcantarillado.setBackground(new java.awt.Color(255, 255, 255));
        txtAlcantarillado.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        txtAlcantarillado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAlcantarillado.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        txtAlcantarillado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlcantarilladoActionPerformed(evt);
            }
        });
        pnlFactura.add(txtAlcantarillado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 110, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setLabelFor(txtAseo);
        jLabel12.setText("ASEO");
        jLabel12.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        pnlFactura.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 40, 20));

        txtAseo.setEditable(false);
        txtAseo.setBackground(new java.awt.Color(255, 255, 255));
        txtAseo.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        txtAseo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAseo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        txtAseo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAseoActionPerformed(evt);
            }
        });
        pnlFactura.add(txtAseo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 40, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setLabelFor(txtSubsidio);
        jLabel13.setText("SUBSIDIO");
        jLabel13.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        pnlFactura.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 60, 20));

        txtSubsidio.setEditable(false);
        txtSubsidio.setBackground(new java.awt.Color(255, 255, 255));
        txtSubsidio.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        txtSubsidio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSubsidio.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        txtSubsidio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubsidioActionPerformed(evt);
            }
        });
        pnlFactura.add(txtSubsidio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 60, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setLabelFor(txtTarifa);
        jLabel14.setText("TARIFA");
        jLabel14.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        pnlFactura.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 70, 20));

        txtTarifa.setEditable(false);
        txtTarifa.setBackground(new java.awt.Color(255, 255, 255));
        txtTarifa.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        txtTarifa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTarifa.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        txtTarifa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTarifaActionPerformed(evt);
            }
        });
        pnlFactura.add(txtTarifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 70, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setLabelFor(txtValorUltimoPago);
        jLabel16.setText("FECHA Y VALOR ULTIMO PAGO");
        jLabel16.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        pnlFactura.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 210, 20));

        txtFechaUltimoPago.setEditable(false);
        txtFechaUltimoPago.setBackground(new java.awt.Color(255, 255, 255));
        txtFechaUltimoPago.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        txtFechaUltimoPago.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFechaUltimoPago.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        txtFechaUltimoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaUltimoPagoActionPerformed(evt);
            }
        });
        pnlFactura.add(txtFechaUltimoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 100, 20));

        txtValorUltimoPago.setEditable(false);
        txtValorUltimoPago.setBackground(new java.awt.Color(255, 255, 255));
        txtValorUltimoPago.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        txtValorUltimoPago.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValorUltimoPago.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        txtValorUltimoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorUltimoPagoActionPerformed(evt);
            }
        });
        pnlFactura.add(txtValorUltimoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 110, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("CONCEPTO DE COBRO");
        jLabel17.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        pnlFactura.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 570, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        pnlFactura.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 410, 20));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setLabelFor(txtConsumo);
        jLabel21.setText("CONSUMO");
        jLabel21.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        pnlFactura.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 110, 40));

        txtConsumo.setEditable(false);
        txtConsumo.setBackground(new java.awt.Color(255, 255, 255));
        txtConsumo.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        txtConsumo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtConsumo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        txtConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsumoActionPerformed(evt);
            }
        });
        pnlFactura.add(txtConsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 110, 60));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setLabelFor(txtTotalPresente);
        jLabel19.setText("TOTAL PRESENTE");
        jLabel19.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        pnlFactura.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 110, 40));

        txtTotalPresente.setEditable(false);
        txtTotalPresente.setBackground(new java.awt.Color(255, 255, 255));
        txtTotalPresente.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        txtTotalPresente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalPresente.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        txtTotalPresente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalPresenteActionPerformed(evt);
            }
        });
        pnlFactura.add(txtTotalPresente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 110, 60));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setLabelFor(txtMesesDeuda);
        jLabel22.setText("<html><center>MESES DE<center>DEUDAS<html>");
        jLabel22.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        pnlFactura.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 70, 40));

        txtMesesDeuda.setEditable(false);
        txtMesesDeuda.setBackground(new java.awt.Color(255, 255, 255));
        txtMesesDeuda.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        txtMesesDeuda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMesesDeuda.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        txtMesesDeuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMesesDeudaActionPerformed(evt);
            }
        });
        pnlFactura.add(txtMesesDeuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 70, 60));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setLabelFor(txtReconexion);
        jLabel26.setText("Reconexión");
        jLabel26.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel26.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        pnlFactura.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 60, 20));

        txtReconexion.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        txtReconexion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtReconexion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        txtReconexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReconexionActionPerformed(evt);
            }
        });
        pnlFactura.add(txtReconexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 100, 20));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setLabelFor(txtMatricula);
        jLabel27.setText("Matricula");
        jLabel27.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel27.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jLabel27.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlFactura.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 60, 40));

        txtMatricula.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        txtMatricula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMatricula.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        txtMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculaActionPerformed(evt);
            }
        });
        pnlFactura.add(txtMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 100, 14));

        jLabel46.setBackground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("________");
        jLabel46.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel46.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        jLabel46.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        pnlFactura.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 70, 10));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setLabelFor(txtTotalOtrosSaldos);
        jLabel23.setText("OTROS SALDOS PENDIENTES");
        jLabel23.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        pnlFactura.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 160, 40));

        txtTotalOtrosSaldos.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        txtTotalOtrosSaldos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalOtrosSaldos.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        txtTotalOtrosSaldos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalOtrosSaldosActionPerformed(evt);
            }
        });
        pnlFactura.add(txtTotalOtrosSaldos, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 100, 20));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setLabelFor(txtTotalPagar);
        jLabel20.setText("<html><center>TOTAL A PAGAR <center>ACUEDUCTO<html>");
        jLabel20.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        pnlFactura.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 120, 40));

        txtTotalPagar.setEditable(false);
        txtTotalPagar.setBackground(new java.awt.Color(255, 255, 255));
        txtTotalPagar.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        txtTotalPagar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalPagar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        txtTotalPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalPagarActionPerformed(evt);
            }
        });
        pnlFactura.add(txtTotalPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 120, 60));

        jLabel29.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel29.setText("  OBSERVACIONES");
        jLabel29.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel29.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jLabel29.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlFactura.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 290, 30));

        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("  Si pagas tendrás un servicio de mejor calidad");
        jLabel18.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        pnlFactura.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 290, 30));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("<html>______________________________ <center>Junta de accion comunal de Emaus<html>");
        jLabel25.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 0, 0)));
        pnlFactura.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 280, 60));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Vigilada por superintendencia de servicios públicos ssp");
        pnlFactura.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 560, 20));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pnlFactura.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 500, 10));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Emaus.png"))); // NOI18N
        pnlFactura.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 340, 86));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel34.setLabelFor(txtFacturaNumero);
        jLabel34.setText("FACTURA: ");
        pnlFactura.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 70, 20));

        txtFacturaNumero.setEditable(false);
        txtFacturaNumero.setBackground(new java.awt.Color(255, 255, 255));
        txtFacturaNumero.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        txtFacturaNumero.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFacturaNumero.setText("0");
        txtFacturaNumero.setBorder(null);
        txtFacturaNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFacturaNumeroActionPerformed(evt);
            }
        });
        pnlFactura.add(txtFacturaNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, 80, 22));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setLabelFor(txtNombreSuscriptor);
        jLabel35.setText("NOMBRE DEL SUSCRIPTOR");
        jLabel35.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        jLabel35.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlFactura.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 190, 30));

        txtNombreSuscriptor.setEditable(false);
        txtNombreSuscriptor.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreSuscriptor.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        txtNombreSuscriptor.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        txtNombreSuscriptor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreSuscriptorActionPerformed(evt);
            }
        });
        pnlFactura.add(txtNombreSuscriptor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 190, 20));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setLabelFor(txtCodigoSuscriptor);
        jLabel36.setText("CODIGO");
        jLabel36.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        jLabel36.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlFactura.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, 70, 30));

        txtCodigoSuscriptor.setEditable(false);
        txtCodigoSuscriptor.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigoSuscriptor.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        txtCodigoSuscriptor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigoSuscriptor.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        txtCodigoSuscriptor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoSuscriptorActionPerformed(evt);
            }
        });
        pnlFactura.add(txtCodigoSuscriptor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 70, 20));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setLabelFor(txtMesFacturadoSuscriptor);
        jLabel37.setText("MES FACTURADO");
        jLabel37.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        jLabel37.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlFactura.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, 100, 30));

        txtMesFacturadoSuscriptor.setEditable(false);
        txtMesFacturadoSuscriptor.setBackground(new java.awt.Color(255, 255, 255));
        txtMesFacturadoSuscriptor.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        txtMesFacturadoSuscriptor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMesFacturadoSuscriptor.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        txtMesFacturadoSuscriptor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMesFacturadoSuscriptorActionPerformed(evt);
            }
        });
        pnlFactura.add(txtMesFacturadoSuscriptor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, 100, 20));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setLabelFor(txtFEmisionSuscriptor);
        jLabel38.setText("<html>FECHA DE <center>EMISIÓN<html>");
        jLabel38.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        jLabel38.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlFactura.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, 70, 30));

        txtFEmisionSuscriptor.setEditable(false);
        txtFEmisionSuscriptor.setBackground(new java.awt.Color(255, 255, 255));
        txtFEmisionSuscriptor.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        txtFEmisionSuscriptor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFEmisionSuscriptor.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        txtFEmisionSuscriptor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFEmisionSuscriptorActionPerformed(evt);
            }
        });
        pnlFactura.add(txtFEmisionSuscriptor, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, 70, 20));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setLabelFor(txtPOportunoSuscriptor);
        jLabel40.setText("<html><center>PAGO<center>OPORTUNO<html>");
        jLabel40.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jLabel40.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlFactura.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 70, 30));

        txtPOportunoSuscriptor.setEditable(false);
        txtPOportunoSuscriptor.setBackground(new java.awt.Color(255, 255, 255));
        txtPOportunoSuscriptor.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        txtPOportunoSuscriptor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPOportunoSuscriptor.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        txtPOportunoSuscriptor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPOportunoSuscriptorActionPerformed(evt);
            }
        });
        pnlFactura.add(txtPOportunoSuscriptor, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 530, 70, 20));

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setLabelFor(txtFSuspensionSuscriptor);
        jLabel41.setText("<html><center>FECHA DE<center>SUSPENSIÓN<html>");
        jLabel41.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        jLabel41.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlFactura.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, 70, 30));

        txtFSuspensionSuscriptor.setEditable(false);
        txtFSuspensionSuscriptor.setBackground(new java.awt.Color(255, 255, 255));
        txtFSuspensionSuscriptor.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        txtFSuspensionSuscriptor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFSuspensionSuscriptor.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        txtFSuspensionSuscriptor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFSuspensionSuscriptorActionPerformed(evt);
            }
        });
        pnlFactura.add(txtFSuspensionSuscriptor, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 530, 70, 20));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setLabelFor(txtConsumoSuscriptor);
        jLabel42.setText("CONSUMO");
        jLabel42.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        jLabel42.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlFactura.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 190, 30));

        txtConsumoSuscriptor.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        txtConsumoSuscriptor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtConsumoSuscriptor.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        txtConsumoSuscriptor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsumoSuscriptorActionPerformed(evt);
            }
        });
        pnlFactura.add(txtConsumoSuscriptor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 190, 60));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setLabelFor(txtTPresenteSuscriptor);
        jLabel43.setText("<html><center>TOTAL<center>PRESENTE<html>");
        jLabel43.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        jLabel43.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlFactura.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 550, 70, 30));

        txtTPresenteSuscriptor.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        txtTPresenteSuscriptor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTPresenteSuscriptor.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        txtTPresenteSuscriptor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTPresenteSuscriptorActionPerformed(evt);
            }
        });
        pnlFactura.add(txtTPresenteSuscriptor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 580, 70, 60));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setLabelFor(txtMDeudaSuscriptor);
        jLabel31.setText("MESES DE DEUDAS");
        jLabel31.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        jLabel31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlFactura.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 550, 100, 30));

        txtMDeudaSuscriptor.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        txtMDeudaSuscriptor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMDeudaSuscriptor.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        txtMDeudaSuscriptor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMDeudaSuscriptorActionPerformed(evt);
            }
        });
        pnlFactura.add(txtMDeudaSuscriptor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 580, 100, 60));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("<html>OTROS SALDOS <center>PENDIENTES<html>");
        jLabel39.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jLabel39.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlFactura.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, 140, 30));

        txtOSaldosSuscriptor.setEditable(false);
        txtOSaldosSuscriptor.setBackground(new java.awt.Color(255, 255, 255));
        txtOSaldosSuscriptor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOSaldosSuscriptor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        txtOSaldosSuscriptor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOSaldosSuscriptorActionPerformed(evt);
            }
        });
        pnlFactura.add(txtOSaldosSuscriptor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 620, 80, 20));

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setLabelFor(txtReconexionSuscriptor);
        jLabel44.setText("Reconexión");
        jLabel44.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel44.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        pnlFactura.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 580, 60, 20));

        txtReconexionSuscriptor.setEditable(false);
        txtReconexionSuscriptor.setBackground(new java.awt.Color(255, 255, 255));
        txtReconexionSuscriptor.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        txtReconexionSuscriptor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtReconexionSuscriptor.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        txtReconexionSuscriptor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReconexionSuscriptorActionPerformed(evt);
            }
        });
        pnlFactura.add(txtReconexionSuscriptor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 580, 80, 20));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel45.setLabelFor(txtMatriculaSuscriptor);
        jLabel45.setText("Matricula");
        jLabel45.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel45.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jLabel45.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlFactura.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 600, 60, 40));

        txtMatriculaSuscriptor.setEditable(false);
        txtMatriculaSuscriptor.setBackground(new java.awt.Color(255, 255, 255));
        txtMatriculaSuscriptor.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        txtMatriculaSuscriptor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMatriculaSuscriptor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        txtMatriculaSuscriptor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculaSuscriptorActionPerformed(evt);
            }
        });
        pnlFactura.add(txtMatriculaSuscriptor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 600, 80, 15));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("_______");
        jLabel28.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel28.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        jLabel28.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        pnlFactura.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 610, 60, 10));

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setLabelFor(txtTotalAcueducto);
        jLabel47.setText("<html><center>TOTAL<center>ACUEDUCTO<html>");
        jLabel47.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        jLabel47.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlFactura.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 550, 70, 30));

        txtTotalAcueducto.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        txtTotalAcueducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalAcueducto.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        txtTotalAcueducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalAcueductoActionPerformed(evt);
            }
        });
        pnlFactura.add(txtTotalAcueducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 580, 70, 60));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Codigo");

        txtBuscar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-search-24.png"))); // NOI18N
        btnBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnImprimir)
                        .addGap(8, 8, 8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(41, 41, 41)
                .addComponent(btnImprimir)
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFechaSuspensionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaSuspensionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaSuspensionActionPerformed

    private void txtFechaDeEmisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaDeEmisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaDeEmisionActionPerformed

    private void txtPagoOportunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPagoOportunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPagoOportunoActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsumoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsumoActionPerformed

    private void txtMesFacturadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMesFacturadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesFacturadoActionPerformed

    private void txtMesesVencidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMesesVencidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesesVencidosActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtAseoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAseoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAseoActionPerformed

    private void txtAlcantarilladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlcantarilladoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlcantarilladoActionPerformed

    private void txtSubsidioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubsidioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubsidioActionPerformed

    private void txtTarifaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTarifaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTarifaActionPerformed

    private void txtFechaUltimoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaUltimoPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaUltimoPagoActionPerformed

    private void txtTotalPresenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalPresenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalPresenteActionPerformed

    private void txtTotalPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalPagarActionPerformed

    private void txtValorUltimoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorUltimoPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorUltimoPagoActionPerformed

    private void txtNombreSuscriptorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreSuscriptorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreSuscriptorActionPerformed

    private void txtMesesDeudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMesesDeudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesesDeudaActionPerformed

    private void txtOSaldosSuscriptorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOSaldosSuscriptorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOSaldosSuscriptorActionPerformed

    private void txtCodigoSuscriptorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoSuscriptorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoSuscriptorActionPerformed

    private void txtReconexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReconexionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReconexionActionPerformed

    private void txtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculaActionPerformed

    private void txtFSuspensionSuscriptorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFSuspensionSuscriptorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFSuspensionSuscriptorActionPerformed

    private void txtFacturaNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFacturaNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFacturaNumeroActionPerformed

    private void txtMesFacturadoSuscriptorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMesFacturadoSuscriptorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesFacturadoSuscriptorActionPerformed

    private void txtConsumoSuscriptorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsumoSuscriptorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsumoSuscriptorActionPerformed

    private void txtMDeudaSuscriptorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMDeudaSuscriptorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMDeudaSuscriptorActionPerformed

    private void txtFEmisionSuscriptorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFEmisionSuscriptorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFEmisionSuscriptorActionPerformed

    private void txtPOportunoSuscriptorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPOportunoSuscriptorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPOportunoSuscriptorActionPerformed

    private void txtTPresenteSuscriptorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTPresenteSuscriptorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTPresenteSuscriptorActionPerformed

    private void txtTotalAcueductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalAcueductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalAcueductoActionPerformed

    private void txtReconexionSuscriptorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReconexionSuscriptorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReconexionSuscriptorActionPerformed

    private void txtMatriculaSuscriptorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaSuscriptorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculaSuscriptorActionPerformed

    private void txtTotalOtrosSaldosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalOtrosSaldosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalOtrosSaldosActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        try {
            int code = Integer.valueOf(txtBuscar.getText());
            modelo.Acueducto suscriptor = controller.obtenerSuscriptor(code);
            if (suscriptor != null) {
                JOptionPane.showMessageDialog(rootPane, "Busqueda exitosa del suscriptor.",
                        "Busqueda", JOptionPane.INFORMATION_MESSAGE);
                txtNombre.setText(suscriptor.getNombres() + " " + suscriptor.getApellidos());
                txtDireccion.setText(suscriptor.getDireccion());
                txtCodigo.setText(String.valueOf(suscriptor.getCodigo()));
                txtFechaDeEmision.setText(suscriptor.getfEmision());
                txtPagoOportuno.setText(suscriptor.getPagoOportuno());
                txtFechaSuspension.setText(suscriptor.getfSuspension());
                txtMesFacturado.setText(suscriptor.getMesFacturado());
                txtMesesVencidos.setText(String.valueOf(suscriptor.getMesesVencidos()));
                txtAlcantarillado.setText(suscriptor.getAlcantarillado());
                txtAseo.setText(suscriptor.getAseo());
                txtTarifa.setText(suscriptor.getTarifa());
                txtSubsidio.setText(suscriptor.getSubsidio());
                txtConsumo.setText(suscriptor.getConsumo());
                txtTotalPresente.setText("$" + String.valueOf(suscriptor.getTotalPresente()));
                txtMesesDeuda.setText(String.valueOf(suscriptor.getMesesDeuda()));
                txtMatricula.setText(String.valueOf(suscriptor.getMatricula()));
                txtReconexion.setText(String.valueOf(suscriptor.getReconexion()));
                txtTotalOtrosSaldos.setText("$" + String.valueOf(suscriptor.getReconexion() + suscriptor.getMatricula()));
                txtTotalPagar.setText("$" + String.valueOf(suscriptor.getTotalPagar()));
                txtFacturaNumero.setText(txtFacturaNumero.getText() + String.valueOf(suscriptor.getCodigo()));
                txtNombreSuscriptor.setText(suscriptor.getNombres() + " " + suscriptor.getApellidos());
                txtCodigoSuscriptor.setText(String.valueOf(suscriptor.getCodigo()));
                txtFEmisionSuscriptor.setText(suscriptor.getfEmision());
                txtPOportunoSuscriptor.setText(suscriptor.getPagoOportuno());
                txtFSuspensionSuscriptor.setText(suscriptor.getfSuspension());
                txtMesFacturadoSuscriptor.setText(suscriptor.getMesFacturado());
                txtConsumoSuscriptor.setText(suscriptor.getConsumo());
                txtTPresenteSuscriptor.setText("$" + String.valueOf(suscriptor.getTotalPresente()));
                txtMDeudaSuscriptor.setText(String.valueOf(suscriptor.getMesesDeuda()));
                txtMatriculaSuscriptor.setText(String.valueOf(suscriptor.getMatricula()));
                txtReconexionSuscriptor.setText(String.valueOf(suscriptor.getReconexion()));
                txtOSaldosSuscriptor.setText("$" + String.valueOf(suscriptor.getReconexion() + suscriptor.getMatricula()));
                txtTotalAcueducto.setText("$" + String.valueOf(suscriptor.getTotalPagar()));
            } else {
                JOptionPane.showMessageDialog(rootPane, "Busqueda fallida no se encontro el suscriptor.",
                        "Busqueda", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "ERROR...Digite un codigo...", "Busqueda", JOptionPane.ERROR_MESSAGE);
            e.getMessage();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
        try {
            Toolkit tk = pnlFactura.getToolkit();
            PrintJob pj = tk.getPrintJob(this, null, null);
            Graphics g = pj.getGraphics();
            pnlFactura.print(g);
            g.dispose();
            pj.end();
            JOptionPane.showMessageDialog(rootPane, "PDF generado exitosamente","PDF",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            e.getMessage();
            JOptionPane.showMessageDialog(rootPane, "No se logro generar el PDF","PDF",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerarFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnlFactura;
    private javax.swing.JTextField txtAlcantarillado;
    private javax.swing.JTextField txtAseo;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigoSuscriptor;
    private javax.swing.JTextField txtConsumo;
    private javax.swing.JTextField txtConsumoSuscriptor;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFEmisionSuscriptor;
    private javax.swing.JTextField txtFSuspensionSuscriptor;
    private javax.swing.JTextField txtFacturaNumero;
    private javax.swing.JTextField txtFechaDeEmision;
    private javax.swing.JTextField txtFechaSuspension;
    private javax.swing.JTextField txtFechaUltimoPago;
    private javax.swing.JTextField txtMDeudaSuscriptor;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtMatriculaSuscriptor;
    private javax.swing.JTextField txtMesFacturado;
    private javax.swing.JTextField txtMesFacturadoSuscriptor;
    private javax.swing.JTextField txtMesesDeuda;
    private javax.swing.JTextField txtMesesVencidos;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreSuscriptor;
    private javax.swing.JTextField txtOSaldosSuscriptor;
    private javax.swing.JTextField txtPOportunoSuscriptor;
    private javax.swing.JTextField txtPagoOportuno;
    private javax.swing.JTextField txtReconexion;
    private javax.swing.JTextField txtReconexionSuscriptor;
    private javax.swing.JTextField txtSubsidio;
    private javax.swing.JTextField txtTPresenteSuscriptor;
    private javax.swing.JTextField txtTarifa;
    private javax.swing.JTextField txtTotalAcueducto;
    private javax.swing.JTextField txtTotalOtrosSaldos;
    private javax.swing.JTextField txtTotalPagar;
    private javax.swing.JTextField txtTotalPresente;
    private javax.swing.JTextField txtValorUltimoPago;
    // End of variables declaration//GEN-END:variables
}
